services:
  vendor-panel:
    build: .
    container_name: vendor-panel
    ports:
      - "5173:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
